# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gLpebMv7WMxYNPPPr84FYqU2okHBgife
"""

# creating csv file to store trade history
import csv
fields = ['Name', 'lot size', 'buy price', 'sell price', 'PNL']
filename = "trade_history.csv"
with open(filename, 'w') as csvfile:
  csvwriter= csv.writer(csvfile)
  csvwriter.writerow(fields)